# API List
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';


@rootURl = http://localhost:8000

### Check server status
GET {{rootURl}}

# Register Users

### User Register
POST {{rootURl}}/api/v1/auth/register 
Content-Type: application/json

{
    "fName":"anish",
    "lName":"gurung",
    "email":"ac@g.com",
    "password":"12345"
}