# API List



@rootURl = http://localhost:8000

### Check server status
GET {{rootURl}}

# Register Users

### User Register
POST {{rootURl}}/api/v1/auth/register 
Content-Type: application/json

{
    "fName":"ans",
    "lName":"gurung",
    "email":"ae@g.com",
    "password":"12345"
}

# Activating the users
### POSTMehod
POST {{rootURl}}/api/v1/auth/activate-user 
Content-Type: application/json

{
"sessionid":"6801ff9337fddabf0cf0d56f",
"t":"0420a943-a172-4789-b4ae-b8139cfd378e"
}

# Login User
### Login
POST {{rootURl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"specialbishes9@gmail.com",
    "password": "Adamghat7*"

}

# GET USER
### GET
GET {{rootURl}}/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NTY2MzMyOSwiZXhwIjoxNzQ1NjY2OTI5fQ.a1Ee8Owot1qx1vfLaNL8ZB5Dd8v3mL9D4Ahv85mQesE   

###GET New AccessJWT
GET {{rootURl}}/api/v1/auth/renew-jwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NTY2MzMyMCwiZXhwIjoxNzQ4MjU1MzIwfQ.l9vrQ4hlicj_vJKoWJw1pX5NS8lY88SJAfxrcuKTLhg

### Random Otp
POST {{rootURl}}/api/v1/auth/psw-reset
Content-Type: application/json

{
    "email":"specialbishes9@gmail.com"
}

### Password Reset
POST {{rootURl}}/api/v1/auth/update-password
Content-Type: application/json

{
    "email":"specialbishes9@gmail.com",
    "password":"Adamghat7@",
    "randomOTP":7165
}

#Books API Endpoints
###GET
GET {{rootURl}}/api/v1/books

###POST Books
POST {{rootURl}}/api/v1/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NjQ5NDQxMCwiZXhwIjoxNzQ2NDk4MDEwfQ.5JbAeBW9wPSJS48xHUkfTvezRj4g1FUXvXHHiHGCesk 

{
    "title": "The Pragmatic Programmer",
    "year": 1999,
    "author": "Andrew Hunt",
    "imgUrl": "https://example.com/pragmatic.jpg",
    "isbn": "2564123654789",
    "genre": "Programming",
    "description":"This is the best book"
    
    
}

### Get Books for Users
GET {{rootURl}}/api/v1/books
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NjIyMzYwOSwiZXhwIjoxNzQ2MjI3MjA5fQ.CYs4w-JOWHSW2flMfx4Hv_mTaBQ2jBBK1faq4Osu-qg 

### GEt Books for Admins
GET {{rootURl}}/api/v1/books/admin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NzcyMDQ1NSwiZXhwIjoxNzQ3NzI0MDU1fQ.s0eb8CoJiRqn1HdcZUGOXe20psBdkjxtYw-tbijx3kc

### Update Books
PUT {{rootURl}}/api/v1/books
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NzcyMDQ1NSwiZXhwIjoxNzQ3NzI0MDU1fQ.s0eb8CoJiRqn1HdcZUGOXe20psBdkjxtYw-tbijx3kc

    {
      "_id": "68174bd9ce3d36f6d1d93335",
      "status": "inactive",
      "title": "Javascript the book",
      "year": "1997",
      "author": "Lab Bhandari",
      "imgUrl": "https://example.com/pragmatic.jpg",
      "genre": "Programming",
      "available": true,
      "description": "sdfasdfsda",
      "expectedAvailable": null,
      "slug": "python-the-book"
      
    }

### Borrow Books
POST {{rootURl}}/api/v1/borrows
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0NzcyMTM2NCwiZXhwIjoxNzQ3NzI0OTY0fQ.Z-HXhcsaIrxh5uThEEFWAaoRd8RSxcI-kN40zPMoekw

[
     {
    "bookId":"682c1925d2f73be1a8bcd320",
    "thumbnail":"https://m.media-amazon.com/images/I/41SH-SvWPxL.jpg",
    "bookTitle":"Clean Code: A Handbook of Agile Software Craftsmanship"

    }
]

### return book
PATCH {{rootURl}}/api/v1/borrows
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0ODc4Mzg2NCwiZXhwIjoxNzQ4Nzg3NDY0fQ.ug5MAKTP02euXfqjo-POYpsCyVYO1aLpSpVo8NnCedE
{
    "_id": "68343e0b089b9bc4aac2ea21"
}

### Create Reviews
###POST Reviews
POST {{rootURl}}/api/v1/reviews
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0OTYzNzQyNywiZXhwIjoxNzQ5NjQxMDI3fQ.3mmf1Tw9hiIKNO9xn_OWVpVWMjDaGuD9BcAUFlDRVKM 

{
    "bookId":"68343deaff67281f0ec61a5c",
    "title": "Awesome Book",
    "reviewMessage": "This is the awesome  book i have ever read",
    "rating": 5,
    "borrowId":"68343e0b089b9bc4aac2ea21"
}

### GET Reviews
GET {{rootURl}}/api/v1/reviews
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwZWNpYWxiaXNoZXM5QGdtYWlsLmNvbSIsImlhdCI6MTc0OTcxMjU3OSwiZXhwIjoxNzQ5NzE2MTc5fQ.CKV1HQa-pEMm6T4IY6stGa2wrEYKGApKnAQ9VKLvr64
