# API List



@rootURl = http://localhost:8000

### Check server status
GET {{rootURl}}

# Register Users

### User Register
POST {{rootURl}}/api/v1/auth/register 
Content-Type: application/json

{
    "fName":"ans",
    "lName":"gurung",
    "email":"ae@g.com",
    "password":"12345"
}

# Activating the users
### POSTMehod
POST {{rootURl}}/api/v1/auth/activate-user 
Content-Type: application/json

{
"sessionid":"6801ff9337fddabf0cf0d56f",
"t":"0420a943-a172-4789-b4ae-b8139cfd378e"
}

# Login User
### Login
POST {{rootURl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"specialbishes9@gmail.com",
    "password": "Adamghat7#"

}

